export const EGYPT_GOVERNORATES = [
    { id: 'cairo', name: 'القاهرة', nameEn: 'Cairo' },
    { id: 'giza', name: 'الجيزة', nameEn: 'Giza' },
    { id: 'alexandria', name: 'الإسكندرية', nameEn: 'Alexandria' },
    { id: 'dakahlia', name: 'الدقهلية', nameEn: 'Dakahlia' },
    { id: 'red_sea', name: 'البحر الأحمر', nameEn: 'Red Sea' },
    { id: 'beheira', name: 'البحيرة', nameEn: 'Beheira' },
    { id: 'fayoum', name: 'الفيوم', nameEn: 'Fayoum' },
    { id: 'gharbia', name: 'الغربية', nameEn: 'Gharbia' },
    { id: 'ismailia', name: 'الإسماعيلية', nameEn: 'Ismailia' },
    { id: 'monufia', name: 'المنوفية', nameEn: 'Monufia' },
    { id: 'minya', name: 'المنيا', nameEn: 'Minya' },
    { id: 'qalyubia', name: 'القليوبية', nameEn: 'Qalyubia' },
    { id: 'new_valley', name: 'الوادي الجديد', nameEn: 'New Valley' },
    { id: 'suez', name: 'السويس', nameEn: 'Suez' },
    { id: 'aswan', name: 'أسوان', nameEn: 'Aswan' },
    { id: 'assiut', name: 'أسيوط', nameEn: 'Assiut' },
    { id: 'beni_suef', name: 'بني سويف', nameEn: 'Beni Suef' },
    { id: 'port_said', name: 'بورسعيد', nameEn: 'Port Said' },
    { id: 'damietta', name: 'دمياط', nameEn: 'Damietta' },
    { id: 'sharkia', name: 'الشرقية', nameEn: 'Sharkia' },
    { id: 'south_sinai', name: 'جنوب سيناء', nameEn: 'South Sinai' },
    { id: 'kafr_el_sheikh', name: 'كفر الشيخ', nameEn: 'Kafr El Sheikh' },
    { id: 'matrouh', name: 'مطروح', nameEn: 'Matrouh' },
    { id: 'luxor', name: 'الأقصر', nameEn: 'Luxor' },
    { id: 'qena', name: 'قنا', nameEn: 'Qena' },
    { id: 'north_sinai', name: 'شمال سيناء', nameEn: 'North Sinai' },
    { id: 'sohag', name: 'سوهاج', nameEn: 'Sohag' },
];
